### ISSUE TITLE
generateCurrentNumber() returns long but validateCurrentNumber() accepts an int

### ISSUE THREAD

**Issue by seantcanavan** [j256/two-factor-auth#13]
What's up with this mismatch? Am I missing something with how the library should be used?

`public static boolean validateCurrentNumber(String base32Secret, int authNumber, int windowMillis)`

`public static long generateCurrentNumber(String base32Secret) throws GeneralSecurityException`

**Comment by j256** [comment]
Thanks @seantcanavan .  Just poor consistence.  Thanks.

**Comment by seantcanavan** [comment]
thanks for the fix!
