### ISSUE TITLE
qrImageUrl invalid for google authenticator

### ISSUE THREAD

**Issue by RealZimboGuy** [j256/two-factor-auth#16]
great lib, slight issue with the Url generated, is not valid for google authenticator, working sample code below

    public static String qrImageUrl(String keyId, String secret) {
        StringBuilder sb = new StringBuilder(128);
        sb.append("https://chart.googleapis.com/chart?")
                .append("chs=200x200&")
                .append("cht=qr&")
                .append("chld=M|0&")
                .append("chl=")
                .append("otpauth://totp/")
                .append(keyId)
                .append("?secret=")
                .append(secret);
        return sb.toString();
    }

**Comment by j256** [comment]
Sorry, can you explain the difference?

**Comment by RealZimboGuy** [comment]
Hi @j256  sorry missed the email notif, 
so there are two "chl" tags and also the ? and = either side of the "secret" should not be url encoded. i was just testing using my phone to make sure that the image could be scanned and loaded.

eg
Current Code = https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=200x200&chld=M|0&cht=qr&chl=otpauth://totp/TEST%3Fsecret%3DO7F6BWF2PTVVJZJQ
Proposed method = https://chart.googleapis.com/chart?chs=200x200&cht=qr&chld=M|0&chl=otpauth://totp/TEST?secret=O7F6BWF2PTVVJZJQ

-J

**Comment by j256** [comment]
Sorry @RealZimboGuy but I feel that the current URL is correct.  chl needs to be an encoded URL. 
 It has to be encoded because it is the _value_ of chl.  Actually, I wonder if I need to encode the slashes as well. There can't be 2 '?' characters in the URL so that needs to be encoded.

**Comment by RealZimboGuy** [comment]
@j256 just re-tested those above urls with google auth and both worked this time but two days ago it was flat out failing. i honestly have no idea unless my phone updated in the last two days. Sorry for wasting your time. I get what you are saying about if some of the url is encoded should all of it be encoded. hmmm i guess i will leave that up to you to decide.
