### ISSUE TITLE
generateCurrentNumberString cannot match with the authenticator's code

### ISSUE THREAD

**Issue by Ye37Xin** [j256/two-factor-auth#22]
Hi,
Thank you for the insights!
I was playing around the code, and I noticed that when testing the Example program, the code been generated by generateCurrentNumberString does not match with the code provided by Authenticator even at the first time(i know the code would change), but even for the fist appeared code in Authenticator cannot matched with the output, do you possibly know the reason?

**Comment by Ye37Xin** [comment]
Never mind, I found the issue. Thank you

**Comment by antonbowe** [comment]
Could you tell us? I have the same issue and I dont unterstand.

**Comment by j256** [comment]
What problem are you having @antonbowe ?  Make sure your device's time is up-to-date.
