### ISSUE TITLE
code is not validating

### ISSUE THREAD

**Issue by priyankatech2513** [j256/two-factor-auth#30]
i have implemented this code in my android application qr generation and scanning is okay but i am unable to validate code generated but google authenticator app validateCurrentNumber() function always returns false. i also check code of 6 digits which always return different value from google authenticator app. please help and guide me how can validate otp. thanks in advance

**Comment by j256** [comment]
Can you give some examples @priyankatech2513 ?  Are you sure the clock in your device is correct?  Maybe some sort of time zone issue?
