### ISSUE TITLE
Problem with invalid base-32 secret causing ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by WangChangQin** [j256/two-factor-auth#5]
in decodeBase32 this method,if i use "admin" this secret,it can't calculate the true key and it must be crash, 3ku.

**Comment by j256** [comment]
Admin should have been encoded as a base32 value @WangChangQin.   This is part of the spec if you look at: https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm

**Comment by WangChangQin** [comment]
I got it! 3ku.

**Comment by WangChangQin** [comment]
in TimeBasedOneTimePasswordUtil class,this method  decodeBase32  perhaps is wrong. i  know "admin" this value should  encoded as a base32 value,but in your method ,it will show  this exception "java.lang.ArrayIndexOutOfBoundsException: length=3; index=3" .

**Comment by WangChangQin** [comment]
if i use other method replace decodeBase32 ,It will run correctly,even if i import admin

**Comment by j256** [comment]
Well that's a good point.  "admin" is _not_ valid base32 but my code doesn't handle bad strings appropriately.  That's been fixed.
