### ISSUE TITLE
google authenticator 不是有效的身份验证令牌

### ISSUE THREAD

**Issue by ValueInvest** [j256/two-factor-auth#9]
我扫描这个二维码提示我
https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl=200x200&chld=M|0&cht=qr&chl=otpauth://totp/aaa@qq.com%3Fsecret%3DIMWCMR6NJWK3PDBH
google authenticator 不是有效的身份验证令牌

**Comment by KeanuAscent** [comment]
here's one reason is that .there are blank or tab or enter space in this txt, so cause this problem

**Comment by KeanuAscent** [comment]
字符串里包含空格会导致这个问题,并且在安卓设备上会被忽略, 在iso 系统下会提示这个错误

**Comment by KeanuAscent** [comment]
but of course , there's other reason could cause this problem

**Comment by qdongxu** [comment]
Just for curious, I scanned the QR with google authenticator on Iphone, and succeeded.

**Comment by Ye37Xin** [comment]
I had the same issue, when using iphone to scan the QR code, it shows invalid barcode too. But when i manually input the secret key, the userName, it can direct to the correct page. Maybe it is the issue of iso system.

**Comment by j256** [comment]
Anyone know of something that the code can be doing better?

**Comment by j256** [comment]
I'm going to close this now @ValueInvest but please reopen if you have more details.
